import { title } from "process";

export const Data = [
  {
    img: "/products/product1.png",
    title: "Nike Air Max Pulse",
    category: "Womens Shoes",
  },
  {
    img: "/products/product2.png",
    title: "Nike Air Max Pulse",
    category: "Mens Men",
  },
  {
    img: "/products/product3.png",
    title: "Nike Air Max 97 SE",
    category: "Mens Shoes",
  },
];

export const DataGearUp = [
  {
    img: "/gearup/gearup1.png",
    title: "Nike Dri-FIT ADV TechKnit Ultra",
    category: `Mens Short-Sleeve \n Running Top`,
  },
  {
    img: "/gearup/gearup2.png",
    title: "Nike Dri-FIT Challenger",
    category: "Mens 18cm (approx.) 2-in-1 Versatile Shorts",
  },
  {
    img: "/gearup/gearup3.png",
    title: "Nike Dri-FIT ADV Run Division",
    category: "Womens Long-Sleeve Running Top",
  },
  {
    img: "/gearup/gearup4.png",
    title: "Nike Fast",
    category: "Womens Mid-Rise 7/8 Running Leggings with Pockets",
  },
];

export const ProductPageData = [
  {
    img: "/products/productImg1.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg2.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg3.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg4.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg5.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg6.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg7.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg8.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg9.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg1.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg2.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg3.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg4.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg5.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg6.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg7.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg8.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg9.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg1.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg2.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg3.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg4.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg5.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg6.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg7.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg8.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg9.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg1.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg2.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg3.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg4.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg5.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg6.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg7.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg8.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
  {
    img: "/products/productImg9.png",
    title: "Nike Air Force 1 Mid '07",
    tag: "Mens Shoes",
    color: "1 Colour",
    price: "MRP : ₹ 10 795.00",
  },
];
